#!/bin/sh
# Install the apps saved by savejugtest.
set -x
set -e
WINEJUGS=${WINEJUGS:-$HOME/jugs}
export WINEJUGS

for verb in `cd $WINEJUGS; ls`
do
   WINEPREFIX=$HOME/.wine-cloned-$verb
   export WINEPREFIX
   rm -rf $WINEPREFIX
   time sh clonejug $verb
done
