#!/bin/sh
# There's a lot of stuff here that probably doesn't need to be tested, e.g., 
# setting dlls to native, and different windows versions. It doesn't hurt to test
# and may find weird problems. Plus, that way we can test every function.
# Currently not tested:
# ogg - broken

set -ex

rm -rf $HOME/.winetrickscache
WINEPREFIX=${WINEPREFIX:-$HOME/.wine}

for verb in \
    ahk \
    art2kmin \
    cc580 \
    colorprofile \
    comctl32.ocx \
    controlpad \
    corefonts \
    d3dx9 \
    dcom98 \
    dirac \
    dotnet11 \
    dotnet20 \
    dotnet30 \
    droid \
    ffdshow \
    firefox \
    flash \
    fontfix \
    fontsmooth-bgr \
    fontsmooth-disable \
    fontsmooth-gray \
    fontsmooth-rgb \
    gdiplus \
    gecko \
    gecko-dbg \
    hosts \
    ie6 \
    jet40 \
    liberation \
    mdac25 \
    mdac27 \
    mdac28 \
    mfc40 \
    mono20 \
    mono22 \
    mshflxgd \
    msi2 \
    msls31 \
    msmask \
    msscript \
    msxml3 \
    msxml4 \
    msxml6 \
    quicktime72 \
    riched20 \
    riched30 \
    shockwave \
    tahoma \
    urlmon \
    vb2run \
    vb3run \
    vb4run \
    vb5run \
    vb6run \
    vc2005express \
    vcrun6 \
    vcrun2003 \
    vcrun2005 \
    vcrun2005sp1 \
    vcrun2008 \
    vcrun2008sp1 \
    vjrun20 \
    vlc \
    wenquanyi \
    wininet \
    wme9 \
    wmp9 \
    wmp10 \
    wsh56 \
    wsh56js \
    wsh56vb \
    xact \
    xvid \
    fakeie6 \
    allfonts \
    native_mdac \
    volnum \
    nt40 \
    win98 \
    win2k \
    winxp \
    vista \
    version \
    native_oleaut32 \

do
    wineserver -k || true
    rm -rf $WINEPREFIX
    sh winetricks  -q -v $verb
done

# Known to have problems

# Ignores -q
for verb in \
    allcodecs \
    directx9 \
    divx \
    icodecs \
    kde \
    ole2 \
    openwatcom \
    psdk2003
do
    wineserver -k || true
    rm -rf $WINEPREFIX
    sh winetricks -v $verb
done

exit 0
