#!/bin/sh
# Regression test for wisotool2

set -x

errors=0
fail()
{
    echo FAIL: $@
    errors=`expr $errors + 1`
}

case "$LANG" in
""|"C") echo "Some games won't install in the Posix locale; doing 'export LANG=en_US.UTF-8'" ; export LANG=en_US.UTF-8;;
esac

case "$OS" in
 "Windows_NT")
    # Mostly unimplemented...
    # Cheezy fix for getting rid of double slashes when running cygwin in wine
    case "$HOME" in
      /) HOME="" ;;
    esac
    WINE=""
    WINESERVER=true
    DRIVE_C="C:/"
    ;;
 *)
    export WINE=${WINE:-$HOME/wine-git/wine}
    export WINESERVER=${WINESERVER:-$HOME/wine-git/server/wineserver}
    ;;
esac

srcdir=`dirname $0`
srcdir=`cd $srcdir; pwd`

test_speed()
{
    (time sh wisotool2 $1) 2> time.log > /dev/null
    t=`awk '/real/ {print $2}' < time.log`
    minutes=`echo $t | sed 's/m.*//'`
    seconds=`echo $t | sed 's/.*m//;s/s//;s/\..*//'`
    seconds=`expr $seconds + $minutes \* 60`
    echo test_speed: wisotool2 $1 took $seconds seconds
    # Longest runtime as of 11 Dec 2010 is 5 seconds on an e8400 with cygwin
    if test $seconds -gt 7
    then
        fail "test_speed: wisotool2 $1 took $seconds seconds"
    fi
}

test_app_checksums()
{
    # Verify the installation
    if [ -f "$srcdir/wisotoolverify.d/$app.sha1sum" ]
    then
        windir="`$WINE cmd /c echo "%windir%" | cut -c 4- | tr -d '\015'`"
        progdir="`$WINE cmd /c echo "%ProgramFiles%" | cut -c 4- | tr -d '\015'`"

        cd "$DRIVE_C"
        # Fix up the filenames, which can differ between Windows versions/Wine:
        # FIXME: we need a way to guarantee that all _original_ .sha1sums are the same.
        # Preferably generated under 32-bit wine, so that we don't need a really complex sed
        # substitution here...
        sed -e "s|/Program\ Files/|/$progdir/|" -e "s|/windows/|/$windir/|" < "$srcdir/wisotoolverify.d/$app.sha1sum" > $app.sha1sum.tmp
        if ! sha1sum -c $app.sha1sum.tmp 
        then
            fail "test_app_checksum $app !" 
        fi
        rm $app.sha1sum.tmp
        cd $srcdir
    fi
}

test_app()
{
    app=$1

    export WINEPREFIX=$HOME/wisotooltest-prefixes/$app
    DRIVE_C="$WINEPREFIX/dosdevices/c:"

    # change if you don't want to skip ones already installed
    if test -d $HOME/wisotooltest-prefixes/$app
    then
        echo "Skipping $app, already installed"
        return 0
        #rm -rf $WINEPREFIX
    fi
    mkdir -p $WINEPREFIX

    # Isolate us from the user's home directory
    sh -x winetricks sandbox gecko

    echo "Installing $app"
    if ! sh wisotool2 -q $app
    then
        fail "test_app $app failed!"
        return
    fi
    echo -n "Done installing $app, disk usage "
    du -sh $WINEPREFIX
    $WINESERVER -w
    echo "Wineserver done."
    ps augxw | grep exe

    test_app_checksums
}

test_install_cached_or_download()
{
    for a in `sh wisotool2 list-cached list-download | sort -u`
    do
        test_app $a
    done
    sh wisotool2 list-cached > cached.txt
    sh wisotool2 list-download > download.txt
    comm -23 download.txt cached.txt > download-but-not-cached.txt
    if test `wc -l < download-but-not-cached.txt` != 0
    then
        fail "test_install_cached_or_download: asked to install all downloadable apps, but some not listed as cached afterwards"
    fi
}

test_speed list
test_speed list-download
test_speed list-cached
test_speed list-installed
test_install_cached_or_download

echo "Test over, $errors failures."
test $errors = 0
