#!/bin/sh
# Verify that wisotool verbs run to completion
# Optional arg: which group of verbs to run.  Default is 'all'.

set -x
export WINE=$HOME/wine-git/wine
wineserver=$HOME/wine-git/server/wineserver
srcdir=`basename $0`
srcdir=`cd $srcdir; pwd`

# verbs known to not work yet
BLACKLIST="starcraft$|passmark7"

case "$1" in
all|"") verbs="`sh wisotool ls | egrep -v "$BLACKLIST" `" ;;
activision) verbs="
	blur
	codmw2
	" ;;
ea) verbs="
	bfbc2
	cnc3_demo                
	deadspace
	dragonage
	fifa10_demo
	fifaonline3_beta         
	hphbp
	hphbp_demo
	nfsps_demo               
	nfsshift
	nfsshift_demo
	sims3
	spore 
	" ;;
	# Hangs:
	# masseffect2

ubisoft) verbs="
	assassinscreed
	avatar_demo  
	popsot
	popsot_demo
	" ;;
*) echo "Guessing you specified a single verb"; verbs=$1;;
esac

for app in $verbs
do
    export WINEPREFIX=$HOME/.wine-wisotooltest-$app
    rm -rf $WINEPREFIX
    # Isolate us from the user's home directory
    sh winetricks sandbox
    echo "Installing $app"
    time sh wisotool $app
    echo -n "Done installing $app, disk usage "
    du -sh $WINEPREFIX
    $wineserver -w
    echo "Wineserver done."
    ps augxw | grep exe
done
