#!/bin/sh
# Install a few apps, then save them in jugs
set -x
set -e
WINEJUGS=$HOME/jugs 
export WINEJUGS
rm -rf $WINEJUGS
mkdir $WINEJUGS

WINESERVER=${WINESERVER:-wineserver}

# verbs known to not work yet
BLACKLIST="starcraft$"

for verb in `sh wisotool ls | egrep -v "$BLACKLIST" `
do
   WINEPREFIX=$HOME/.wine-staging-$verb
   export WINEPREFIX
   rm -rf $WINEPREFIX
   time sh winetricks sandbox
   time sh wisotool $verb
   time $WINESERVER -w
   time sh savejug $verb
done
