#!/bin/sh
# There's a lot of stuff here that probably doesn't need to be tested, e.g., 
# setting dlls to native, and different windows versions. It doesn't hurt to test
# and may find weird problems. Plus, that way we can test every function.

set -ex

rm -rf $HOME/.winetrickscache
WINEPREFIX=${WINEPREFIX:-$HOME/.wine}

for verb in \
    art2kmin \
    atmlib \
    colorprofile \
    comctl32 \
    comctl32.ocx \
    corefonts \
    d3dx9 \
    dcom98 \
    dinput8 \
    dirac \
    directplay \
    dotnet11 \
    dotnet20 \
    droid \
    fakeie6 \
    ffdshow \
    flash \
    fontfix \
    fontsmooth-bgr \
    fontsmooth-disable \
    fontsmooth-gray \
    fontsmooth-rgb \
    gdiplus \
    gecko \
    gecko-dbg \
    hosts \
    jet40 \
    liberation \
    mdac25 \
    mdac27 \
    mdac28 \
    mfc40 \
    mfc42 \
    mingw \
    mingw-gdb \
    mono20 \
    mono22 \
    mono24 \
    mozillabuild \
    mshflxgd \
    msi2 \
    msls31 \
    msmask \
    msscript \
    msxml3 \
    msxml4 \
    msxml6 \
    openwatcom \
    pdh \
    physx \
    quicktime72 \
    riched20 \
    riched30 \
    richtx32 \
    shockwave \
    tahoma \
    urlmon \
    vb2run \
    vb3run \
    vb4run \
    vb5run \
    vb6run \
    vcrun6 \
    vcrun6sp6 \
    vcrun2003 \
    vcrun2005 \
    vcrun2008 \
    vjrun20 \
    wenquanyi \
    wininet \
    wme9 \
    wmp9 \
    wmp10 \
    wsh56 \
    wsh56js \
    wsh56vb \
    xact \
    xvid \
    ahk \
    firefox \
    ie6 \
    mpc \
    vlc \
    allfonts \
    fakeie6 \
    glsl-disable \
    glsl-enable \
    native_mdac \
    native_oleaut32 \
    nocrashdialog \
    orm=backbuffer \
    orm=fbo \
    orm=pbuffer \
    sandbox \
    sound=alsa \
    sound=audioio \
    sound=coreaudio \
    sound=esound \
    sound=jack \
    sound=nas \
    sound=oss \
    winver=nt40 \
    winver=win98 \
    winver=win2k \
    winver=winxp \
    winver=vista \
    winver= \
    version \
    volnum

do
    wineserver -k || true
    rm -rf $WINEPREFIX
    sh winetricks  -q -v $verb
done

# Known to have problems

if [ "$1" = "--all" ]
then
    # Ignores -q
    for verb in \
        allcodecs \
        cmake \
        cygwin \
        directx9 \
        divx \
        dotnet11sdk \
        dotnet20sdk \
        icodecs \
        kde \
        ole2 \
        psdk2003 \
        psdkwin7 \
        python26 \
        python-comtypes \
        vc2005sp1 \
        vc2005trial
    do
        wineserver -k || true
        rm -rf $WINEPREFIX
        sh winetricks -v $verb
    done
fi

# Broken
#    controlpad #Broken on 64-bit karmic
#    dotnet20sp2
#    dotnet30 
#    fm20
#    ogg
#    psdkvista
#    vc2005express
#    vc2005expresssp1

exit 0
